### ISSUE TITLE
Odd person position?

### ISSUE THREAD

**Issue by petehamilton** [chpatrick/labmap-web#4]
Someone is appearing off the main lab map. [See Here](http://www.freeimagehosting.net/newuploads/164fd.png) or below.

![Weird Position](http://www.freeimagehosting.net/newuploads/164fd.png)

**Comment by chpatrick** [comment]
Yeah, I have a Perl script that generates photos from SVG paths but it's a massive hack, I'll give you the base SVG if you'd like to fix it.
