### ISSUE TITLE
Display message if lab is closed/daemon is stopped

### ISSUE THREAD

**Issue by chpatrick** [chpatrick/labmap-web#7]
If the lab is closed, the JSON should contain only closed => true, and stopped => true if the daemon closed cleanly. The frontend should display these messages.

**Comment by petehamilton** [comment]
We could add [Facebox JS](http://defunkt.io/facebox/) (same one github use?) to do nice dialogue boxes letting the user know?

**Comment by chpatrick** [comment]
Go for it. :)

**Comment by petehamilton** [comment]
Ok, will implement.

**Comment by petehamilton** [comment]
Fixed in pull #8
